require 'rubygems'
require 'rake'
require 'bundler'
Bundler::GemHelper.install_tasks

require 'uglifier'
require 'sprockets'
require 'haml'

require 'compass'

ROOT = File.dirname(File.expand_path('./',__FILE__))
ASSETS_PATH = File.expand_path('./assets', __FILE__)

COFFEE = File.expand_path('./coffee', ASSETS_PATH)
TEMPLATES = File.expand_path('./templates', ASSETS_PATH)
SASS = File.expand_path('./sass', ASSETS_PATH)
IMAGES = File.expand_path('./images', ASSETS_PATH)

Compass.configuration.images_path = IMAGES

class AssetBuilder

  def initialize(env)
    @env = env
  end

  def assets
    @sprockets ||= begin
      Sprockets::Environment.new(ROOT) do |env|
        env.append_path(TEMPLATES)

        compass = Gem.loaded_specs['compass'].full_gem_path
        env.append_path("#{compass}/frameworks/compass/stylesheets")

        if @env == :production
          env.js_compressor = Uglifier.new(copyright: false)
        end
      end
    end
  end

  def render


desc 'Build all assets'
task :build do |t, args|
  puts 'building asset files'



end



### Rake tasks ###

desc 'Run all tests by default'
task :default do
  system("rspec spec")
end

